export default {
    'white':'#FFFFFF',
    'white1':'#F3F7F2',
    'white2':'#E5EDE4',
    'green:':'#497345',
    'green1:':'#64A15E',
    'green2:':'#DCF2DA',
    'green3:':'#93A592',
    // 'orange':,
    // 'red':'',
    // 'red1':'',
    // 'red2':'',
    // 'red3':'',
    // 'red4':'',
    // 'red5':'',
    // 'blue':'',
    // 'blue1':'',
    // 'black':'',
    // 'black1':'',
    // 'black2':'',
    // 'black3':'',
    // 'black4':'',
    // 'black5':'',
}